# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically at runtime by the loader
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${oc.env:OUTPUT_DIR,null}

# path to working directory
work_dir: ${oc.env:WORK_DIR,${paths.root_dir}}
